us_economy_pulse:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT', '6543') | int }}"
      dbname: "{{ env_var('DBT_DATABASE', 'postgres') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      connect_timeout: 30
      keepalives_idle: 0
      sslmode: require
